spring:
  datasource:
    meta:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:postgresql://172.22.101.134:5432/emr?currentSchema=meta
      username: psd
      password: psd1127!@
      hikari:
        poolName: Hikari
        auto-commit: false
    ods:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:oracle:thin:@172.22.101.11:1521/HSSEMRDD
      username: CDWKYK
      password: pltkyk2512f
      hikari:
        poolName: HikariOds
        auto-commit: false
  liquibase:
    # Remove 'faker' if you do not want the sample data to be loaded automatically
    contexts: dev, faker
